name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check index.html
        run: test -f index.html

      - name: Done
        run: echo "CI working 🚀"